# pnpm-workspace.yaml
packages:
  - "apps/*"
  - "apps/web/app/landing"
  - "apps/backend/wildstrikes-socket"
  - "apps/backend/wildstrikes-backend"
  - "packages/*"
  - "packages/phaser-games/wildstrikes"


